// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Categorie struct {
	ID           int32
	CategoryName sql.NullString
	Description  sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type Customer struct {
	ID           int32
	CustomerName sql.NullString
	ContactName  sql.NullString
	Address      sql.NullString
	City         sql.NullString
	PostalCode   sql.NullString
	Country      sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type Employee struct {
	ID        int32
	LastName  sql.NullString
	FirstName sql.NullString
	BirthDate sql.NullString
	Photo     sql.NullString
	Notes     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Order struct {
	ID         int32
	CustomerID sql.NullInt32
	EmployeeID sql.NullInt32
	ShipperID  sql.NullInt32
	OrderDate  sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
}

type OrderDetail struct {
	ID        int32
	OrderID   sql.NullInt32
	ProductID sql.NullInt32
	Quantity  sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Product struct {
	ID          int32
	ProductName sql.NullString
	SupplierID  sql.NullInt32
	CategoryID  sql.NullInt32
	Unit        sql.NullString
	Price       sql.NullFloat64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Shipper struct {
	ID          int32
	ShipperName sql.NullString
	Phone       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Supplier struct {
	ID           int32
	SupplierName sql.NullString
	ContactName  sql.NullString
	Address      sql.NullString
	City         sql.NullString
	PostalCode   sql.NullString
	Country      sql.NullString
	Phone        sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}
